- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1h # Trauma was 2.5
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  guides: # goobstation
  - MedicalDoctor
  - Medical
  - Medicine
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  # <Trauma>
  - !type:OrganChipsSpecial
    chips:
    - SkillChipMedicalDoctor
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      speedModifier: 1.5
    - type: CPRTraining
      reviveChance: 0.45 # a bit better at chest compressions
      inhaleChance: 0.75 # decent at mouth to mouth res.
  # </Trauma>
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical

- type: chameleonOutfit
  id: MedicalDoctorChameleonOutfit
  job: MedicalDoctor
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
