- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 1h # Trauma was 2.5
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  # <Trauma>
  - External
  # </Trauma>
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  # <Trauma>
  guides:
  - MedicalDoctor
  - Medical
  - Medicine
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipParamedic
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
      reviveChance: 0.6 # better at chest compressions
      inhaleChance: 0.9 # very good at mouth to mouth res.
  # </Trauma>

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical

- type: chameleonOutfit
  id: ParamedicChameleonOutfit
  job: Paramedic
  equipment:
    head: ClothingHeadHatParamedicsoft
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatParamedicWB
    gloves: ClothingHandsGlovesLatex
