# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Xenomorph
  name: roles-antag-xenomorph-name
  antagonist: true
  setPreference: true
  objective: roles-antag-xenomorph-objective
  guides: [ Xenomorphs ]
  creditImage: /Textures/_Trauma/EndCredits/Antags/xenos.png
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 2h

- type: antagSpecifier
  id: Xenomorph
  prefRoles: [ Xenomorph ]
  spawnerPrototype: SpawnPointGhostXenomorph
  briefing:
    # SIS-ChatGreeting-Start
    theme:
      titleBackground: "#190e1c"
      titleBorder: "#8c3986"
      messageBackground: "#0d070f"
      messageBorder: "#331538"
      titleText: "#d680d0"
      messageText: "#e4d4e6"
      highlight1: "#e4d4e6"
      highlight2: "#8c3986"
    sections:
    - priority: 0
      title:
        text: role-greeting-title
      message:
        text: xenomorph-role-greeting
    - priority: 1
      title:
        text: role-greeting-desc-title
      message:
        text: xenomorph-role-greeting-desc
    # SIS-ChatGreeting-End
