# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antagSpecifier
  abstract: true
  id: BaseAbductor
  unequipOldGear: true
  briefing:
    sound: /Audio/_Shitmed/Misc/abductor.ogg
    # SIS-ChatGreeting-Start
    theme:
      titleBackground: "#100d1c"
      titleBorder: "#fd0098"
      messageBackground: "#07050d"
      messageBorder: "#2c1236"
      titleText: "#f472b6"
      messageText: "#c8d6e5"
      highlight1: "#00ffcc"
      highlight2: "#fd0098"
    sections:
    - priority: 0
      title:
        text: role-greeting-title
      message:
        text: abductor-role-greeting
    - priority: 1
      title:
        text: role-greeting-desc-title
      message:
        text: abductor-role-greeting-desc
    # SIS-ChatGreeting-End
  components:
  - type: Abductor
  - type: ActionGrant
    actions:
    - ActionReturnToShip
  - type: NpcFactionMember
    factions:
    - SimpleHostile
  - type: Tag
    tags:
    - Abductor
    - AbductorScientist
    - CanPilot
    - FootstepSound
    - DoorBumpOpener
  - type: RandomMetadata
    nameSegments:
    - AbductorScientistPrefix
    - AbductorNames
    nameFormat: name-format-standard

- type: antagSpecifier
  parent: BaseAbductor
  id: LoneAbductor
  spawnerPrototype: LoneAbductorSpawner
  startingGear: LoneAbductorGear
  prefRoles: [ LoneAbductorAntag, AbductorScientistAntag, AbductorAgentAntag ]
  mindRoles: [ MindRoleLoneAbductor ]
  components:
  - type: AbductorScientist
  - type: SurgeryIgnoreClothing
  - type: Sanitized
  - type: SurgerySpeedModifier
    speedModifier: 1.5
  # TODO: does this really need to be here...
  - type: GhostRole
    name: abductor-lone-ghost-role-name
    description: abductor-lone-ghost-role-desc
    rules: abductors-ghost-role-rules
    mindRoles:
    - MindRoleGhostRoleSoloAntagonist
    raffle:
      settings: default
  - type: GhostTakeoverAvailable

- type: antagSpecifier
  parent: BaseAbductor
  id: AbductorScientist
  spawnerPrototype: AbductorScientistSpawner
  startingGear: AbductorScientistGear
  prefRoles: [ AbductorScientistAntag, AbductorAgentAntag ]
  mindRoles: [ MindRoleAbductorScientist ]
  components:
  - type: AbductorScientist
  - type: SurgeryIgnoreClothing
  - type: Sanitized
  - type: SurgerySpeedModifier
    speedModifier: 1.5

- type: antagSpecifier
  parent: BaseAbductor
  id: AbductorAgent
  spawnerPrototype: AbductorAgentSpawner
  startingGear: AbductorAgentGear
  prefRoles: [ AbductorAgentAntag, AbductorScientistAntag ]
  mindRoles: [ MindRoleAbductorAgent ]
  components:
  - type: RandomMetadata
    nameSegments:
    - AbductorAgentPrefix
    - AbductorNames
  - type: AbductorScientist # Remove if you want agents to not be able to use teleporter etc solo

- type: antagSpecifier
  id: AbductorVictim
  mindRoles: [ MindRoleAbductorVictim ]
  briefing:
    sound: /Audio/_Shitmed/Misc/abducted.ogg
    theme:
      titleBackground: "#19140d"   # Грязный сепиевый фон
      titleBorder: "#e67e22"       # Тревожный янтарный сигнал паники
      messageBackground: "#0c0906" # Параноидальная тьма
      messageBorder: "#362412"     # Ржавый контур
      titleText: "#facc15"         # Жёлтая паника (НЕ БЕЛЫЙ)
      messageText: "#ded3c2"       # Мятый пергамент конспиролога (НЕ БЕЛЫЙ)
      highlight1: "#facc15"        # Параноидальный жёлтый (hl1)
      highlight2: "#fd0098"        # Маджента Голосов в голове (hl2)
    sections:
    - priority: 0
      title:
        text: role-greeting-title
      message:
        text: abductor-victim-role-greeting
    - priority: 1
      title:
        text: role-greeting-desc-title
      message:
        text: abductor-victim-role-greeting-desc
  pickPlayer: false # manually assigned
