using Content.SIS.Shared.Respawn;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.SIS.Client.Respawn.UI;

[GenerateTypedNameReferences]
public sealed partial class RespawnWindow : DefaultWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    private readonly SharedRespawnSystem _respawnSystem;

    public RespawnStatusComponent? RespawnStatus;

    public event Action? OnRequestPressed;

    public RespawnWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _respawnSystem = _entitySystem.GetEntitySystem<SharedRespawnSystem>();

        RequestButton.OnPressed += _ => OnRequestPressed?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (RespawnStatus == null)
            return;

        var remaining = _respawnSystem.GetRespawnCooldown(RespawnStatus);
        if (remaining.TotalSeconds > 0)
        {
            RequestButton.Text = Loc.GetString(
                "ghost-respawn-request-role-button-timer",
                ("minutes", $"{remaining.Minutes:00}"),
                ("seconds", $"{remaining.Seconds:00}")
            );
        }
        else
        {
            RequestButton.Disabled = false;
            RequestButton.Text = Loc.GetString("ghost-respawn-request-role-button");
        }
    }
}
