- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-hop
  access:
  - Library # Trauma - replaced Service
  - Maintenance
  # <Trauma>
  special:
  - !type:OrganChipsSpecial
    chips:
    - SkillChipLibrarian
  # </Trauma>

- type: startingGear
  id: LibrarianGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d20Dice
    pocket2: HandLabeler # for making named bestsellers
  storage:
    back:
    # <Trauma>
    - PrintingPressFlatpack
    - Multitool
    - CaneSheathFilled # Temp while I sprite the flaming sword of islam
    # </Trauma>
    - BookRandom

- type: chameleonOutfit
  id: LibrarianChameleonOutfit
  job: Librarian
  equipment:
    head: ClothingHeadHatCanadaBeanie
    eyes: ClothingEyesGlassesJamjar
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedGreen
    outerClothing: ClothingOuterWinterColorGreen
    gloves: ClothingHandsGlovesColorBlack
