using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.IO;

namespace Content.Inky.Client.Administration.Chafa.UI;

[GenerateTypedNameReferences]
public sealed partial class ChafaUi : DefaultWindow
{
    public ChafaUi()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetImage(byte[] imageData)
    {
        try
        {
            var stream = new MemoryStream(imageData);
            ImageDislay.Texture = Texture.LoadFromPNGStream(stream);
        }
        catch { }
    }
}
