- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h
  creditImage: /Textures/_Trauma/EndCredits/Antags/thief.png # Trauma

- type: antagSpecifier
  parent: RestrictedAntag
  id: Thief
  prefRoles:
  - Thief
  allowNonHumans: true
  multiAntagSetting: NotExclusive
  startingGear: ThiefGear
  components:
  - type: Pacified
  - type: Thieving
    stripTimeReduction: 2
    stealthy: true
  mindRoles:
  - MindRoleThief
  briefing:
    sound: "/Audio/Misc/thief_greeting.ogg"
    # SIS-ChatGreeting-Start
    theme:
      titleBackground: "#15181a"
      titleBorder: "#2d3436"
      messageBackground: "#0b0d0e"
      messageBorder: "#1e2224"
      text: "#747d8c"
      highlight1: "#20bf6b"
      highlight2: "#265581"
    # SIS-ChatGreeting-End
- type: startingGear
  id: ThiefGear
  storage:
    back:
    #- ThiefBeacon # DeltaV - no more objectives
    - SatchelThief
    # - ClothingHandsChameleonThief - Goobedit, since thieves have intrinsic pickpocketing now we don't need these
