# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Blob
  name: roles-antag-blob-name
  antagonist: true
  setPreference: true
  objective: roles-antag-blob-objective
  guides: [ Blob ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 2h
  creditImage: /Textures/_Trauma/EndCredits/Antags/blob.png

- type: antagSpecifier
  parent: CommandBlacklistedAntag
  id: Blob
  prefRoles: [ Blob ]
  allowNonHumans: true
  briefing:
    sound: /Audio/Announcements/bloblarm.ogg
    # SIS-ChatGreeting-Start
    theme:
      titleBackground: "#1e2410"
      titleBorder: "#a3e635"
      messageBackground: "#0f1308"
      messageBorder: "#2b3815"
      titleText: "#facc15"
      messageText: "#d9f99d"
      highlight1: "#a3e635"
      highlight2: "#f97316"
    sections:
    - priority: 0
      title:
        text: role-greeting-title
      message:
        text: blob-carrier-role-greeting
    - priority: 1
      title:
        text: role-greeting-desc-title
      message:
        text: blob-carrier-role-greeting-desc
    # SIS-ChatGreeting-End
  mindRoles:
  - MindRoleBlob
